version: '3'
services:
  postgres:
    image: postgres:13.4
    container_name: 'db'
    ports:
      - "3306:3306"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data #MacOSの場合
      # - app_postgre:/var/lib/postgresql/data #Windows
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin-pass'
    restart: always
  app:
    build: .
    image: ruby:2.7.4
    container_name: 'app'
    command: bundle exec rails s -p 80 -b '0.0.0.0'
    ports:
      - "80:80"
    environment:  
      VIRTUAL_PORT: 80
    volumes:
      - .:/app/src
    depends_on:
      - postgres
    restart: always

# #windows
# volumes:
#   app_postgre:
#     external: true
